### ISSUE TITLE
Markers cannot have HTML content as child

### ISSUE THREAD

**Issue by Haapavuo** [GIShub4/solid-map-gl#100]
If you insert HTML content, e.g. a ```<p>``` element within a ```Marker```, you will only get ```[object HTMLParagraphElement]``` instead of the HTML content. I haven't found any workaround to this. A custom component doesn't work either inside a Marker. Only text content seems to work.

```typescript
          <Show when={locs()}>
            <For each={locs()}>{(loc, i) => 
              <Marker lngLat={loc.geometry?.coordinates} options={{ color: 'red' }}>
                <p>{loc.properties.osm_tags?.name}</p>
              </Marker>
            }</For>
          </Show>
```

The above example renders ```[object HTMLParagraphElement]``` to the ```Marker```s.

Any ideas? Thanks.

**Comment by Haapavuo** [comment]
Workaround that actually works until the Marker component gets fixed:

```typescript
let m = new maplibregl.Marker({color: 'yellow'});
    m.setPopup(new maplibregl.Popup().setHTML("<h1>Hello World!</h1>"));
    m.setLngLat(markerLoc).addTo(mapContext.map);
```

**Comment by KaiHuebner** [comment]
Thanks for reporting this issue. Fixed in the latest version.
