### ISSUE TITLE
Add option to use solid component as Marker Element

### ISSUE THREAD

**Issue by m9dfukc** [GIShub4/solid-map-gl#103]
I would like to use a custom `Marker`. There is the option to provide a HTMLElement but this currently only works with `document.createElement` ... any chance to use Solid components for this?  Maybe there is already a way but my soildjs knowledge seems not solid enough 😂 

This works:
```Javascript
const myDiv = document.createElement("div");
const newContent = document.createTextNode("Hi there and greetings!");
myDiv.appendChild(newContent);
...
<Marker
  lngLat={[0, 0]}
  options={{ element: myDiv }}
>
  Hi there! 👋
</Marker>
```

This doesn't:
```Javascript
const TestDiv = () => <div>Hi there and greetings!</div>;
...
<Marker
  lngLat={[0, 0]}
  options={{ element: <TestDiv /> }}
>
  Hi there! 👋
</Marker>
```

The console error I get with the second example: `Uncaught TypeError: Comp is not a function ...`

**Comment by KaiHuebner** [comment]
Hi Andreas,

Thanks for looking into this. I never tried a custom marker.
I tried to replicate your error but it seems to work for me. [Custom Marker Example](https://stackblitz.com/edit/solid-map-gl-marker-popup-yfr9hd?file=src%2Findex.tsx)

Can you update the example and show me where it's not working for you.

Thanks

**Comment by m9dfukc** [comment]
Hmm, interesting ... this works for me as well. But only if I declare the `TestDiv` Component inside the `App` Component. If I separate these it [won't work](https://stackblitz.com/edit/solid-map-gl-marker-popup-va59fs?file=src%2Findex.tsx).

I guess my solidjs knowledge is too limited and the reason this doesn't work has to do with solids compilation order?  Bare with me, this is my first solid project coming from a React background ;) 

... I gonna close this now.

**Comment by KaiHuebner** [comment]
Yes, I noticed the same. It doesn't work when you place the `TestDiv` outside the `Component`.

Maybe try to use the [SolidJS render function](https://www.solidjs.com/docs/latest/api#render) to convert `JSX` to a `DOM Node`.

Let me know if you find a solution and I'm happy to change this library to make it work. 😊

**Comment by m9dfukc** [comment]
Thank you for the hint, I will look into SolidJs render function then ... maybe there is a way to automatically invoke the `render` function for every component that expects an HTMLElement?! Or would this be to performance intense? 

For context what I am trying to do is basically [this](https://lab.gildasp.fr/leaflet-html-overlay/); fully zoomable Html Overlays on top of the map. Unfortunately Mapbox doesn't support Html Layers in that sense and the Markers are the closest that I could find. Ideally I would like to keep my components separate and out of the App Component as I want to build a full blow website with this principle ... but maybe I also need another round of research and Markers are not what I am looking for :) Anyway, the ability to create custom Markers in a separate Component certainly has many other use cases not just my very specific one.

I'll let you know how this works out. Thanks for looking into it so far!
