### ISSUE TITLE
Layer minzoom & maxzoom are broken

### ISSUE THREAD

**Issue by m9dfukc** [GIShub4/solid-map-gl#105]
Looks like Layer Style `minzoom` and `maxzoom` [are broken](https://stackblitz.com/edit/solid-map-gl-geojson-sy8f8g?file=src%2Findex.tsx), same as the Layer `visible` prop (see issue #94).

**Comment by KaiHuebner** [comment]
You may have mixed up `min` and `max`. Please have a look at this [example](https://stackblitz.com/edit/solid-map-gl-geojson-spwnas?file=src%2Findex.tsx)
I shows you the current zoom level. 
It also shows you the working visibility prop.

**Comment by m9dfukc** [comment]
Oh yes you are right I mixed up the two 🤦 ... sorry for the noise.
