### ISSUE TITLE
Support for PMTiles

### ISSUE THREAD

**Issue by aemonm** [GIShub4/solid-map-gl#133]
Thanks for the great project. 

Is it possible to add a custom protocol [as shown in this example](https://docs.protomaps.com/pmtiles/maplibre)? I'm trying to load PMTiles specifically.

**Comment by KaiHuebner** [comment]
Here an [example](https://stackblitz.com/edit/solid-map-gl-protomaps?file=src%2Findex.tsx) showing the use of PMTiles.
