### ISSUE TITLE
1.10.4 does not render map

### ISSUE THREAD

**Issue by russbiggs** [GIShub4/solid-map-gl#137]
Given a simple example with 1.10.4

```js
const App: Component = () => {
  const [viewport, setViewport] = createSignal({
    center: [-122.45, 37.78],
    zoom: 11,
  } as Viewport);

  return (
    <MapGL
      mapLib={maplibre} // <- Pass MapLibre package here
      options={{ style: 'https://demotiles.maplibre.org/style.json' }}
      viewport={viewport()}
      onViewportChange={(evt: Viewport) => setViewport(evt)}
    />
  );
};
```

Does not render a map, and provides no errors in the console:

<img width="1552" alt="Screenshot 2024-02-16 at 6 15 03 PM" src="https://github.com/GIShub4/solid-map-gl/assets/8487728/9972879d-8ce3-4b62-8a37-726533cc8f8a">

Downgrading to 1.10.3 resolves the issue, rendering a map as expected

**Comment by KaiHuebner** [comment]
Thanks for raising this defect. This should be fix now in version 1.10.5
