### ISSUE TITLE
Marker Popup control

### ISSUE THREAD

**Issue by davedbase** [GIShub4/solid-map-gl#15]
It would be wonderful if there was a way to specify if the pop-up should be displayed on load or not ie:
```ts
  <Marker
    lngLat={[location.longitude, location.latitude]}
    options={{ color: "#000", focusAfterOpen: true, open: false }}
    open={false}
  >
     {location.name}
  </Marker>
```
The issue I'm running into is I want the popups to only display when they are clicked on, right now I can't do so without writing my own Popup component.

**Comment by KaiHuebner** [comment]
I added a prop for controling the initial state of the popup on a marker.
You can use it like this (the popup options are nested in the marker options):
```jsx
<Marker
  lngLat={[0, 0]}
  options={{
    color: '#F00',
    popup: { focusAfterOpen: false, closeButton: false },
  }}
  openPopup={false}>
  Hi there! 👋
</Marker>
```

**Comment by davedbase** [comment]
Wonderful! That's so helpful.
