### ISSUE TITLE
MapLibre + Mapbox attributions displaying

### ISSUE THREAD

**Issue by davedbase** [GIShub4/solid-map-gl#16]
Sorry to flood you with issues! None of these are critical though, thanks goodness. I noticed that my implementation is showing attributions for both MapLibre and Mapbox:

![Screen Shot 2022-09-25 at 10 02 09 AM](https://user-images.githubusercontent.com/1168397/192147700-9240f3df-d799-4821-b259-cf9c7e6a1501.png)

I don't actually have MapLibre populated and instead have my Mapbox key. I do have both libraries installed because it complains if they aren't both added. Is there a way to shut both of them off?

**Comment by KaiHuebner** [comment]
Thanks for finding this issue.
That's fixed now. Please get the latest version.
