### ISSUE TITLE
Error when trying to set a Layer's props.id to a variable

### ISSUE THREAD

**Issue by kengreim** [GIShub4/solid-map-gl#172]
I get an error (`Uncaught TypeError: setting getter-only property "id"`) with this sample code:
```ts
<Show when={typeof map.getter() != "undefined"}>
  <Layer
    id={map.name}
    style={{
      "source-layer": map.sourceLayer,
      type: "line",
    }}
    visible={map.getter()}
  />
</Show>
```
I do not get an error with something like `<Layer id="STRING"...`

It may be due to settings `props.id` on this line instead of creating a different id variable that is then used for the rest of the component? Similar to what is done for `sourceId` in the line above it.
https://github.com/GIShub4/solid-map-gl/blob/72b46e81b09a0bae10f52155c2e4f9258ccdffef/src/components/Layer/index.tsx#L95

**Comment by KaiHuebner** [comment]
Thanks for finding this. I think the error message is due to me trying to set the props.id value. I changed it to a local variable.
Should be fixed in the latest release (v1.11.3). Can you please test it.

**Comment by kengreim** [comment]
Will test in the next few days and see if it’s fixed, thanks!

**Comment by kengreim** [comment]
Can confirm it works now with no issues!
