### ISSUE TITLE
Error when trying to create Popup

### ISSUE THREAD

**Issue by kengreim** [GIShub4/solid-map-gl#173]
I get the following error in the console when I try to create a popup: ```Uncaught TypeError: can't access property "Popup", window.MAPLIB is undefined```

Possibly because the Popup component is using `window.MAPLIB` (all caps) while the rest of the library uses `window.MapLib`?

https://github.com/GIShub4/solid-map-gl/blob/72b46e81b09a0bae10f52155c2e4f9258ccdffef/src/components/Popup/index.tsx#L36

**Comment by KaiHuebner** [comment]
Thanks for finding this. Should be fixed in the latest release (v1.11.3).
