### ISSUE TITLE
Error on interactive map example

### ISSUE THREAD

**Issue by davedbase** [GIShub4/solid-map-gl#18]
It looks like the Interactive Map example isn't working as expected: https://stackblitz.com/edit/solid-map-gl-interactive?embed=1&file=src%2FApp.tsx. Actually none of the examples are working due to this error.

![Screen Shot 2022-09-28 at 12 23 30 PM](https://user-images.githubusercontent.com/1168397/192833746-2729cbac-1e3b-46d8-9564-4899971b6264.png)

**Comment by infograafikko** [comment]
Temporarily manual method is to add `maplibre-gl` to `package.json`

**Comment by KaiHuebner** [comment]
Hi David,

I fixed this issue in the latest release. I'm using a different way now to include MapLibre.
Let me know if the latest version fixes it for you.
