### ISSUE TITLE
Documentation identifies onViewportChange accepting an Event

### ISSUE THREAD

**Issue by davedbase** [GIShub4/solid-map-gl#19]
I found a reference in the docs that claims the onViewportChange property accepts a function with Event instead of Viewport: https://gis-hub.gitbook.io/solid-map-gl/components/mapgl#interactive-map

My apologies for not submitting this as a PR. I'll admit I'm rushing through a project right now and it's quicker for me to report as an issue. If I have a moment I can circle back to this in a few weeks and help with a proper PR.

```
onViewportChange={(evt: Event) => setViewport(evt)}
```
Should be
```
onViewportChange={(viewport: Viewport) => setViewport(viewport)}
```

Thanks!

**Comment by KaiHuebner** [comment]
Fixed.
