### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by davedbase** [GIShub4/solid-map-gl#2]
Hi! I was reviewing SolidHack submissions and noticed your work on this project. I attempted a very simple implementation myself a few months back for a project but your is far more advanced.

I'd love to offer you the solid-mapbox handle on GitHub and NPM if you'd take it. I think this project deserves to be in its place. Let me know and I'd be happy to transfer.

**Comment by KaiHuebner** [comment]
Hi David,

Thanks for the appreciation. While working on this library, I came across your project as well. :-)

I based the name of this library on the two libraries I used to start on this one:

- [visgl/react-map-gl](https://github.com/visgl/react-map-gl)
- [urbica/react-map-gl](https://github.com/urbica/react-map-gl)

I'd like to take your offer on using `solid-mapbox`. Do you think it makes devs find it more easy?
And how can I migrate the project without loosing the devs which are already using this library?
It it possible to run the project under two different names or make one deprecated?

Sorry for so many questions. I'm very professional in Mapbox development but new to SolidJS, GitHub and NPM.
Are you maybe interested in contributing or co-maintaining this project?

Thanks again.

Kai

**Comment by KaiHuebner** [comment]
Hi Dave,

I will close this one since it's not an issue with the library.
Please feel free to contact me if you still want to offer me your GitHub and NPM handles.

Thanks.

**Comment by birkskyum** [comment]
@KaiHuebner , I'm working at [MapLibre](https://www.npmjs.com/package/maplibre-gl), an open alternative to Mapbox that started as a fork a few years ago. The API is still quite similar. Could you consider supporting both, like [react-map-gl](https://github.com/visgl/react-map-gl) does?

**Comment by davedbase** [comment]
@birkskyum this is a wonderful idea! I'm a big MapLibre fan and hope to use it and this plugin on my project in the next 2-3 weeks!
