### ISSUE TITLE
What is the correct use of fitBounds?

### ISSUE THREAD

**Issue by davedbase** [GIShub4/solid-map-gl#20]
It's a bit unclear how to properly specify fitBounds. I have a range of markers and I'd like to ensure the viewport contains them all in view. I noticed that Control does allow for me to specify GeolocationOptions which has the `fitBounds` property in it. However when I provide it with proper data the bounds don't take effect.

An example might be helpful for future users as this particular use-case is likely very common.

:-) Thanks!

**Comment by KaiHuebner** [comment]
Here is a simple example:
```jsx
import { render } from 'solid-js/web';
import { Component, createSignal } from 'solid-js';
import MapGL, { Viewport, Marker, useMap } from 'solid-map-gl';

const places = [
  [-0.118092, 51.509865], // London
  [30.523333, 50.450001], // Kyiv
  [2.154007, 41.390205], // Bacelona
];

const [viewport, setViewport] = createSignal({
  center: [0,0],
  zoom: 0,
} as Viewport);

const Root: Component = () => {
  const map = useMap();
  map().fitBounds(places, { padding: 10 });
  return <></>;
};

const App: Component = () => (
  <MapGL
    options={{
      accessToken: import.meta.env.VITE_MAPBOX_ACCESS_TOKEN,
      style: 'mb:basic',
    }}
    viewport={viewport()}
    onViewportChange={(evt: Viewport) => setViewport(evt)}
  >
    {places.map((place) => (
      <Marker lngLat={place} />
    ))}
    <Root />
  </MapGL>
);

render(() => <App />, document.getElementById('root') as HTMLElement);
```

You basically create a nested component which uses the `useMap` context to get access to the mapbox object. And then you can use any functionallity mapbox provides. Sorry haven't documented it yet.

**Comment by KaiHuebner** [comment]
Hi David,

I added this code to the documentation examples.
Let me know if it's working for you.
