### ISSUE TITLE
Input data is not a valid GeoJSON object.

### ISSUE THREAD

**Issue by skreutzberger** [GIShub4/solid-map-gl#23]
I need to provide my map with some GeoJSON data. I am running the example from https://gis-hub.gitbook.io/solid-map-gl/components/source#geojson-source by copy & paste in an `App.tsx` file and the output in my browser's console is

<img width="416" alt="Screen Shot 2022-10-04 at 18 34 23" src="https://user-images.githubusercontent.com/564725/193875316-5734df53-4bdf-4a0c-93b9-fee4de39886e.png">

I am 100% sure that the format is correct since I used it also in a Mapbox React project. Is it is a bug?

Addendum: the same error happens if I turn the `tsx` file into a `jsx` file and remove all types.

**Comment by KaiHuebner** [comment]
Hi Sebastian,

The example had a typo in there. I fixed most of the examples now.
The issue was that the GeoJSON was wrapped in an object. 
Change your code to:
```jsx
<Source
  source={{
    type: 'geojson',
    data: data // <- before data: { data }
  }}
>...</Source>
```

**Comment by skreutzberger** [comment]
Yes it works now, thank you!
