### ISSUE TITLE
TypeScript definitions for event handlers

### ISSUE THREAD

**Issue by shishkin** [GIShub4/solid-map-gl#28]
Currently, event handlers are not part of map or layer props. When used in a strict TS project, adding event handlers to props fails type checking. I also wasn't able to [augment module declarations](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) probably due to props types not being originally declared as interfaces.

Maybe I'm missing something since this project is written in TypeScript. I also noticed that mapbox-gl is typed in Flow and you don't use @types/mapbox-gl in the project. Just wonder what's your main use case for the library and how you go about typings.

**Comment by KaiHuebner** [comment]
Hi Sergey,

I added the missing TypeScript events in the latest release. Please let me know if this fixes your issue.
I will have a look into using `@types/mapbox-gl` in the future.
