### ISSUE TITLE
Source tiles no longer reactive

### ISSUE THREAD

**Issue by russbiggs** [GIShub4/solid-map-gl#35]
I am using solid-map-gl v1.3.9 and dynamically changing a query parameter in my tiles URL via a store as shown here :

```jsx
<Source
  source={{
    id: 'locations',
    type: 'vector',
    tiles: [
      `http://example.com/locations/tiles/{z}/{x}/{y}.pbf?parameter=${
        store.parameter.id
      }`,
    ],
    minzoom: 1,
    maxzoom: 24,
    bounds: [-180, -90, 180, 90],
  }}
>
```

This worked (and continues to work if using v1.3.9) but on upgrading to v1.5.1 a change to ```store.parameter.id``` does not trigger an update on the Source. Changes to ```store.parameter.id``` does trigger update the Layer style definitions successfully so I'm thinking something has regressed in just the Source. I've looked through the changes a bit since 1.3.9 but nothing is jumping out as an obvious change that would cause this.

**Comment by KaiHuebner** [comment]
Fixed in v1.5.2

Pease let me know if it's working for you.

**Comment by KaiHuebner** [comment]
Sorry, I mean: v1.5.3

**Comment by russbiggs** [comment]
Thanks for the quick response. I've tested 1.5.3 and so far looks like it working as expected! Thanks!
