### ISSUE TITLE
Docs for plugin support

### ISSUE THREAD

**Issue by col16** [GIShub4/solid-map-gl#4]
Hi again!

I've worked out how to add the [Geocoder](https://github.com/mapbox/mapbox-gl-geocoder) plugin to my map, by way of the `useMap` function. I think you should add a comment to the README about how to do this, so that others know it's compatible with plugins.

Here's my code, for what it's worth:

```
import { useMap } from "solid-map-gl";
import { Component, onMount } from "solid-js";
import mapboxgl from "mapbox-gl";
import MapboxGeocoder from "@mapbox/mapbox-gl-geocoder";
import "@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css";

const Geocoder: Component = () => {
    const map = useMap();

    onMount(async () => {
        let accessToken = map()._requestManager._customAccessToken;
        map().addControl(
            new MapboxGeocoder({
                accessToken: accessToken,
                mapboxgl: mapboxgl,
            })
        );
    });

    return <></>;
};

export default Geocoder;
```

Cheers,
Cameron

**Comment by KaiHuebner** [comment]
Hi Cameron,

Thanks for that. Yes I really have to document the `useMap` context provider.
I will update my documentation with you example.
