### ISSUE TITLE
Dragging of Marker?

### ISSUE THREAD

**Issue by skreutzberger** [GIShub4/solid-map-gl#43]
I have a MapGL map with a marker in it which all works fine. Now I want to allow the user to drag the marker.

I did set the marker option `draggable: true` as described at https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker but the marker stays put. I am using the default marker CSS. Also the `onDragEnd` event of the marker does not fire. 

Is that a known issue or am I doing it wrong somehow?

**Comment by KaiHuebner** [comment]
Hi Sebastian,

Please have a look at the [Dynamic Marker Example.](https://stackblitz.com/edit/solid-map-gl-marker?embed=1&file=src%2Findex.tsx)
It uses the `draggable` option as well as the `onDragEnd` event.

Please let me know if this helps you.

**Comment by skreutzberger** [comment]
Thanks for the example! It works if I change `draggable:false` to `draggable:true` in line 24.
