### ISSUE TITLE
Use stores to track viewpoint

### ISSUE THREAD

**Issue by col16** [GIShub4/solid-map-gl#5]
Hi again!

I'd like to keep track of the viewpoint in a Store, so that the user can navigate to another page (using the [router](https://github.com/solidjs/solid-app-router)) but when they return have the map in the same place as they left it.

This is pretty similar to #1. Some sample code:

```
const Map: Component = () => {
    const [store, { setViewport }] = useStore();
    const viewport = () => store.map.viewport;

    return (
        <MapGL
            class={styles.Map}
            options={{
                accessToken: <my access token here>,
                style: <style URL here>,
            }}
            viewport={viewport()}
        ></MapGL>
    );
};
```

I had a look at the changes you made in 808429d609bc7b2ec927919fc232f2c66e9830d3, and was going to put together a pull request. But it seems a bit more complex for viewports because you have the `callMove` and `callEnd` functions, and I thought I would get lost.

Thanks!

**Comment by KaiHuebner** [comment]
Hi Cameron,

Sorry for the late reply.
Can you please explain a bit more what you trying to do.

You can pass the `viewport` and `setViewport` signal to central store and reuse it when you come back later to your map page.

The `callMove` method updates the viewport during a transition instead of just when the transition is finished.

**Comment by col16** [comment]
No worries.

I've just had another thing about the problem, and realised that I can put the default viewport in my store and then use that to define the viewport signal:

```
const [viewport, setViewport] = createSignal(store.map.viewport);
```

Then createEffect can be used to record any updates to the viewport in the store:

```
createEffect(() => {
        // Record viewport in store so that it can be restored after
        // user goes to another page and then back to map again
        setStoreViewport(viewport());
    });
```

With these two in place the map location is retained after a user navigates to another page via the router then goes back again.

It's not what I had imagined at first, but still solves my problem nicely.

Thanks for
