### ISSUE TITLE
How to use SVGs URIs as symbols?

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#53]
I would like to to about 20 different SVGs as symbols. How can this be done?

**Comment by KaiHuebner** [comment]
Hi Kevin,

Officially Mapbox doesn't accept SVG's as Images for Markers. See [here](https://github.com/mapbox/mapbox-gl-js/issues/5529) and [here.](https://github.com/mapbox/mapbox-gl-js/issues/8320)
The workaround is to convert the SVG image to ImageData which can be used in WebGL. 
I included this conversion in the latest update, so you don't have to do it.

[Here an example on how to use it.](https://stackblitz.com/edit/solid-map-gl-add-svg-image?file=src%2Findex.tsx)

If the SVG is small you can see jagged edges when its rasterised/converted.
A workaround for this is to create a larger SVG and then scale it down in the `Layer` component with:
[`style={{ 'icon-size': 0.5 }}`](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-size)

Let me know if this fixed your issue.

**Comment by kevinelliott** [comment]
Thank you so much for the quick reply. It means a lot to me. Understood. Let me go and digest your example and see if I can put it to use!

**Comment by kevinelliott** [comment]
This seems to work! Fantastic.

Now how can I access the item's properties from the Layer so that I can pass a type in that will help lookup a specific Image to be used?

**Comment by KaiHuebner** [comment]
In the [example](https://stackblitz.com/edit/solid-map-gl-add-svg-image?file=src%2Findex.tsx) you can see in the beginning I assign a feature property `image` of the random points which determine what image to use for the symbol (img_0 - img_9).
Later I load all the SVG's assignig them the same id's (img_0 - img_9).
In the layer `style -> layout` section I assign the [icon image](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-image) to the feature property `image` .using the [get expression](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#get).

I hope that clears it up.

**Comment by kevinelliott** [comment]
Is there any way to get the value dynamically and pass it to something in the Layout section?

**Comment by KaiHuebner** [comment]
Hi Kevin,
As far a I know, you can't access feature properties in the rendering process. It has to be defined before via the layout and paint properties. Dynamic rendering is done via style expressions.
If you find a different way in the [Mapbox API](https://docs.mapbox.com/mapbox-gl-js/guides/), I'm happy to include it.

**Comment by kevinelliott** [comment]
@KaiHuebner I see, darn!
