### ISSUE TITLE
Present hover & click modals for extended data in GeoJSON source/layer ?

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#54]
How can we hook into hover and click for points that are in a GeoJSON defined by a Source/Layer combo? Would be great to be able to show a minimal popup on hover, and instruct a more formal sticky div for click.

**Comment by KaiHuebner** [comment]
Hi Kevin,

I just updated the [example](https://stackblitz.com/edit/solid-map-gl-add-svg-image?file=src%2Findex.tsx) to show you how to use the hover and click events.

**Comment by KaiHuebner** [comment]
Hi Kevin,
I will close this incident.
Feel free to reopen if you need more information

**Comment by kevinelliott** [comment]
Thank you @KaiHuebner, that is helpful. How would we best expand this to make use of varying solid components that would provide changes to the content, instead of just strings?
