### ISSUE TITLE
How to get map instance w/ useMap() for existing MapGL?

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#55]
Is there a way to get the current `MapboxMap` instance (I want to call `fitBounds()` on it) from an existing MapGL instance in a Component?

**Comment by kevinelliott** [comment]
I figured this out, by using the event's `target` attribute to call `jumpTo()`.

**Comment by kevinelliott** [comment]
Turns out that I still need to access the map instance, so that I can use queryRenderedFeatures to look up a feature to store elsewhere. Any thoughts how to properly ensure that `useMap()` will populate a value for `map` so that it can be used in a click handler?

**Comment by KaiHuebner** [comment]
Hi Kevin,
Please have a look at this [example](https://stackblitz.com/edit/solid-map-gl-fit-bounds?file=src%2Findex.tsx). It uses the `useMap()` context.
As long as the component which uses the context is a child component of `MapGL` then the `useMap()` should be populated with the `map` object.

**Comment by kevinelliott** [comment]
Unfortunately it is not a child component, but in the map component itself. How would I get access to it then?

**Comment by KaiHuebner** [comment]
You can pass the geometry for `queryRenderedFeatures` and the result array via props or a store object.
So you call `queryRenderedFeatures` within the `MapGL` component  but use the input and output outside of the map.

**Comment by kevinelliott** [comment]
> 

Yes, how can I do this in the main component? How do I get the mapgl reference?

**Comment by sachaw** [comment]
Same issue here:
I believe a context provider should be provided containing the ref which is accessed via `useMap()`

**Comment by KaiHuebner** [comment]
The latest version improves the map context.
Now you can access the map object from outside the `MapGL` component.
See [Here](https://stackblitz.com/edit/solid-map-gl-fit-bounds?embed=1&file=src%2Findex.tsx)

Hope that fixes the issue.
