### ISSUE TITLE
How to track/follow an item in GeoJSON?

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#56]
I am dynamically constructing GeoJSON, retrieved at an interval from a remote API. If a user clicks on an item, I would like to be able to keep that item centered, even across interval loads. How might this be possible with solid-map-gl?

**Comment by kevinelliott** [comment]
I managed to do this by using a store and saving this value, then in the map render, checking to see if this item exists in the store and looking it up in the list of saved items, then recentering the map, on a regular interval.

**Comment by KaiHuebner** [comment]
Hi Kevin,

Good that you found a solution already.
Here an [example](https://stackblitz.com/edit/solid-map-gl-track-feature?file=src%2Findex.tsx) showing how to track features.

**Comment by kevinelliott** [comment]
This is pretty close to what I've done.

What I do is store the id of the resource that should be followed/tracked, in a store (via createStore), which the setter is passed down into a component that displays the UI element that enables it.

Then, there is a conditional check to see if the store has the value set, and if so, it pulls out the item from the store where all the elements are stored (which power the geojson). On a regular interval (once a second), it does this check to confirm this is a state, and then updates the viewport to center on the latest value.
