### ISSUE TITLE
How to show buttons to toggle map layers?

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#57]
I tried the example where the buttons existed to change the map type, but the buttons never showed up.

**Comment by KaiHuebner** [comment]
Are you talking about this [example](https://stackblitz.com/edit/solid-map-gl-vector-base) where you change the map style?

For changing the visibility for individual layer, use the following code:
```jsx
const [show, setShow] = createSignal(false);
...
<button onClick={setShow(t => !t)}>Toggle Layer</button>
...
<MapGL ...>
  <Source ...>
    {show && <Layer ... />}
  </Source>
</MapGL>
```

**Comment by kevinelliott** [comment]
Yes, that's what I have implemented, but the buttons themselves are not displaying on the map.

**Comment by KaiHuebner** [comment]
By default the `MapGL` container as the following styles applied (to fill the page):
```css
position: absolute;
inset: 0px;
```
So If you want to display something within the map container you can overwrite the style prop of the `MapGL` component or warp your buttons like this:
```jsx
<div style="position: absolute; z-index:1">
  <button ...>Show</button>
</div>
```

**Comment by kevinelliott** [comment]
That is great @KaiHuebner this solved the issue for me!

**Comment by KaiHuebner** [comment]
I updated the default map container css so you don't need the `div` wrapper anymore.
