### ISSUE TITLE
Setting style of map (via button click) removes sources/layer content and Atmosphere

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#58]
I'm not sure this is intentional, but when the style of the map is changed in globe mode, the atmosphere and all markers from GeoJSON layers are cleared.

**Comment by KaiHuebner** [comment]
Thanks for finding this issue.
It was a tricky one to fix.
Try the latest release and let me know if it's fixed.

**Comment by kevinelliott** [comment]
> Thanks for finding this issue.
> It was a tricky one to fix.
> Try the latest release and let me know if it's fixed.

Thank you! I will try this now.
