### ISSUE TITLE
Triggering content loads on viewport changes?

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#61]
I would like to make bounding box content loads when the viewport changes. What is the best methodology to do this?

**Comment by KaiHuebner** [comment]
Hi Kevin,

The best way would be to listen to the `onViewportChange` event on the `MapGL` component, like:
```jsx
<MapGL
  onViewportChange={evt => console.log(evt)}>
  ...
</MapGL>
```
This will fire every time the map moves and gives you the latest viewport coordinates. 
To calculate the bounding box from the viewport coordinatee you can use: https://github.com/mapbox/geo-viewport
The latest version has a `inTransit` flag in the viewport object, it's false when the map finished moving.

**Comment by kevinelliott** [comment]
I will give this a test. Is the viewport object inside of the event that is passed into the event handler?

**Comment by KaiHuebner** [comment]
Yes, the event in `onViewportChange` is the viewport object.
