### ISSUE TITLE
Creation of circles around a point?

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#62]
I would like to create some concentric circles outward around a point (a selection), designating distances from the center visually.

Since I wasn't able to find anything specific for doing this, I created some Postgres PostGIS that calculates using:

```
ST_AsGeoJSON(ST_Buffer(ST_SetSRID(ST_MakePoint(${station.longitude}, ${station.latitude}), 4326), 0.5, 'quad_segs=16'))
```

However this draws an oval on the globe.

I'm wondering if there's a better way to handle this?

**Comment by KaiHuebner** [comment]
Hi Kevin,

I think if you create a circle polygon in GeoJSON you will always have problems with projection distortion.
Another option is to just use the point geometry and render a circle layer on the client side, like:
```jsx
<Layer
  style={{
    type: 'circle',
    paint: {
      'circle-radius': 50,
      'circle-color': 'red',
      'circle-opacity': 0.5,
      'circle-pitch-alignment': 'map',
    },
  }}></Layer>
```

The `circle-pitch-alignment` lays the circle flat on the map. [See Style Docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-pitch-alignment)

<img width="500" alt="Screenshot 2023-04-09 at 19 15 50" src="https://user-images.githubusercontent.com/7897443/230771999-3ba159e6-c019-40ed-a451-7a9ed81f4659.png">
