### ISSUE TITLE
Layer priority?

### ISSUE THREAD

**Issue by kevinelliott** [GIShub4/solid-map-gl#63]
Is there an equivalent to `z-index` for layers? I noticed that when drawing some GeoJSON content with opacity, that markers from other layers are respected at outward zooms, but as the zoom comes in, the items appear more behind the lower opacity content.

**Comment by KaiHuebner** [comment]
Hi Kevin,

The layer order is determined by the child order in the `MapGL` component, like:
```jsx
<MapGL> 
  <Layer>A</Layer>
  <Layer>B</Layer>
</MapGL>
``` 
Renders to: Base Style -> Layer A -> Layer B -> Top
So Layer B will be on top of Layer A.

Markers and Popups will always be rendered on top of everything, except when you use a symbol layer as a marker.

**Comment by kevinelliott** [comment]
Thank you. I will take a look closer and see if that can be mitigated using proper ordering there. Though, I'm wondering why this current scenario occurs only when zoomed in at some level.

**Comment by KaiHuebner** [comment]
The layer order should not be affected by the zoom level. If you looking for a ordering of features within a layer, there is a `sort-key` style property for that. [See Mapbox style docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-circle-circle-sort-key)
