### ISSUE TITLE
No Viewport component installed

### ISSUE THREAD

**Issue by BrightLynk** [GIShub4/solid-map-gl#65]
Hi, should there be a 'Viewport' component? It is used in the example code but not in the install. I'm not using Typescript at the moment so maybe that is my problem
Thank you

**Comment by KaiHuebner** [comment]
Hi BrightLynk,
The map viewport is handled by the `MapGL` component.
The import you see in the example code is a viewport typescript type. This can be used to make sure that the viewport object is in the right format. But if you're not using typescript you can ignore this part.
If you want to do some more sophisticated things, like viewport rotation or 3d translation, then you can use the `Camera` component.
