### ISSUE TITLE
MapLibre v3 and `supported()` 

### ISSUE THREAD

**Issue by korzhyk** [GIShub4/solid-map-gl#66]
`TypeError: mapLib.supported is not a function`

https://github.com/GIShub4/solid-map-gl/blob/fc35853a0501a9192b93c396947cbc10d163a173/src/components/MapGL/index.tsx#L133

Sience version 3 [MapLibre GL](https://github.com/maplibre/maplibre-gl-js) does not exports `supported()` https://github.com/maplibre/maplibre-gl-js/pull/2591

**Comment by KaiHuebner** [comment]
Fixed in the last release
[Demo](https://stackblitz.com/edit/solid-map-gl-use-maplibre)
