### ISSUE TITLE
Layer `featureState` will not update when feature id is `0`

### ISSUE THREAD

**Issue by korzhyk** [GIShub4/solid-map-gl#67]
https://github.com/GIShub4/solid-map-gl/blob/fc35853a0501a9192b93c396947cbc10d163a173/src/components/Layer/index.tsx#L150

We can expect `featureState.id` can be `0` when [`generateId = true`](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-generateId) so in that case `id` will correspond to the array index of the feature.

**Comment by KaiHuebner** [comment]
This should be fixed in the latest version.
Can you please test and let me know if it's working.

**Comment by korzhyk** [comment]
@KaiHuebner I'm confirm, works as expected
[Demo](https://stackblitz.com/edit/solid-map-gl-use-maplibre-htfmeg?file=src%2Findex.tsx)
