### ISSUE TITLE
Map on[Event] prop support for layerId option

### ISSUE THREAD

**Issue by russbiggs** [GIShub4/solid-map-gl#8]
I would like to set some event listeners on a specific layer via the 3 argument option such as in ```onMouseEnter``` i.e. 

https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:mouseenter

```js
map.on('mouseenter', 'mylayer', () => console.log('foo'))
```

From what i'm seeing here: https://github.com/GIShub4/solid-map-gl/blob/main/src/components/MapGL/index.tsx#L148 is doesn't seem like 3 arguments are supported by solid-map-gl, just the event and callback style. In some cases certain events allow 2 or 3 arguments e..g [```dblclick```](https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:dblclick). Am I missing something? Happy to contribute if this is really not currently supported and there would be interest in building in support for these event handlers.

**Comment by KaiHuebner** [comment]
Hi Russ,

Thanks for finding this issue. I totally missed it.
I just fixed it, so please upgrade to the latest version.

You can now use the event listeners like before:
```jsx
<MapGL
  ...
  onClick={ () => console.log('map click') }
/>
```
or using an object where the keys are the layerId's:
```jsx
<MapGL
  ...
  onClick={{
    water: () => console.log('water layer click'),
    landuse: () => console.log('landuse layer click'),
  }}
/>
```

It is also possible to use the event listeners on the individual layer component:
```jsx
<MapGL>
  <Source>
    <Layer
      ...
      onClick={ () => console.log('layer click') }
    />
  </Source>
</MapGL>
```

**Comment by russbiggs** [comment]
Thanks for such a quick update. I am trying to access the map object in some of these callbacks like this (in vanilla js):

```js
map.on('mouseenter', 'clusters', () => {
  map.getCanvas().style.cursor = 'pointer'
})
map.on('mouseleave', 'clusters', () => {
  map.getCanvas().style.cursor = ''
})
```

I generally see how I could do the event listener but is it possible to access the map object in the callback via the on[Event] prop? I've tried the ```useMap``` function but that doesnt seem to work.

**Comment by KaiHuebner** [comment]
If you just want to change the cursor, than do it like this:
```jsx
const [viewport, setViewport] = createSignal({
  center: [-84.5, 44.18],
  zoom: 6,
} as Viewport)

const [cursorStyle, setCursorStyle] = createSignal('grab')

const App = () => (
  <MapGL
    options={{
      accessToken: MAPBOX_ACCESS_TOKEN,
      style: 'mb:street',
    }}
    cursorStyle={cursorStyle()}
    onMouseOver={{ water: () => setCursorStyle('pointer') }}
    onMouseLeave={{ water: () => setCursorStyle('grab') }}
    viewport={viewport()}
    onViewportChange={(evt: Viewport) => setViewport(evt)}></MapGL>
)
```

I will have a look later today to see how you can access the map object within the event listener and let you know.

**Comment by russbiggs** [comment]
Thanks that makes sense. Here's another example where having access to the map object in an event listener is needed but maybe isnt covered by the MapGL component like the example above: 

```
map.on("click", 'myLayerId', (e) => map.queryRenderedFeatures(e.point));
```

https://docs.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures/

**Comment by KaiHuebner** [comment]
After some research if found out that the event object holds a reference to the map object.
So just try this:
```jsx
const [viewport, setViewport] = createSignal({
  center: [-84.5, 44.18],
  zoom: 6,
} as Viewport)

const [layerId, setLayerId] = createSignal('')

export const App = () => (
  <MapGL
    options={{
      accessToken: MAPBOX_ACCESS_TOKEN,
      style: 'mb:street',
    }}
    viewport={viewport()}
    onViewportChange={(evt: Viewport) => setViewport(evt)}
    onMouseMove={(evt: any) => {
      const features = evt.target.queryRenderedFeatures(evt.point)
      setLayerId(features[0]?.layer.id)
    }}>
    <h2>{layerId()}</h2>
  </MapGL>
)
```
I tested it on the individual layers too. No need for the map context here.

**Comment by russbiggs** [comment]
Good find! Thanks for looking into this. Really enjoying the library so far!

**Comment by KaiHuebner** [comment]
Thank you for the appreciation.

I will create some examples explaining the event handling a bit more. Documentation is a bit thin on this.
Feel free to reopen or create a new issue if you have more problems.
This helps me to make this library better.
