### ISSUE TITLE
onLoad is not getting fired

### ISSUE THREAD

**Issue by m9dfukc** [GIShub4/solid-map-gl#91]
The `onLoad` event on MapGL is not getting fired. I did a quick [inspection of the source code](https://github.com/GIShub4/solid-map-gl/blob/73cd69da40795819fe40a19cdf9946d1c93d9a0d/src/components/MapGL/index.tsx#L191) and found that the events only get attached after the "load" has fired and hence the "onLoad" never gets fired as the "load" event is already finished.

**Comment by KaiHuebner** [comment]
Thanks for finding this bug.
Fixed in the [latest release](https://github.com/GIShub4/solid-map-gl/releases/tag/v1.9.3)
