### ISSUE TITLE
CustomLayer visible prop has no effect

### ISSUE THREAD

**Issue by m9dfukc** [GIShub4/solid-map-gl#94]
I have the need for imperatively switching a CustomLayer on and off, unfortunately the `visible` [Prop](https://gis-hub.gitbook.io/solid-map-gl/components/layer) has no effect here and results in a thrown error if switched dynamically with a signal:

`Error: The layer 'cl-168' does not exist in the map's style and cannot be styled.`

**Comment by KaiHuebner** [comment]
Thanks for reporting this issue. Fixed in the latest version.

**Comment by m9dfukc** [comment]
Hi. Are you sure this is fixed? [Doesn't work for me](https://stackblitz.com/edit/solid-map-gl-geojson-sy8f8g?file=src%2Findex.tsx%3AL55), not with CustomLayers neither with "regular" layers.

**Comment by KaiHuebner** [comment]
Please have a look at this [example](https://stackblitz.com/edit/solid-map-gl-geojson-spwnas?file=src%2Findex.tsx)
It shows you the two ways you can toggle layer visibility.

I found a minor issue with static boolean values but it works fine with reactive props (signals, stores).
I will try to fix the static value issue.
