### ISSUE TITLE
MapGL element produces an empty div

### ISSUE THREAD

**Issue by Haapavuo** [GIShub4/solid-map-gl#98]
Seems like the following component produces an empty div when used:

```typescript
import MapGL, { Source, Layer } from "solid-map-gl";
import 'mapbox-gl/dist/mapbox-gl.css';

export function MapTest(props) {
  return (
    <MapGL
      options={{
        style: 'mb:light',
        accessToken: "MY_SECRET",
      }}
      viewport={{
        center: [-122.41, 37.78],
        zoom: 11,
      }}
    >
      <Source
        source={{
          type: 'geojson',
          data: 'https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson',
        }}
      >
        <Layer
          style={{
            type: 'circle',
            paint: {
              'circle-radius': 5,
              'circle-color': 'red',
            },
          }}
        />
      </Source>
    </MapGL>
  );
};

export default MapTest;
```

Usage on a page:
```typescript
<MapTest />
```

I am doing this in a 'export default function Page()' instead of a 'const App: Component = () => ...'. Does this matter?

No errors show up on console (Browser or server).

Any ideas? Thanks.

**Comment by KaiHuebner** [comment]
Hi Jeri,

It's working for me when I copy the above code into a black project. I'm using [solid-start](https://start.solidjs.com/).
Can you please give me a bit more information about your project setup and maybe create a sample project on [stackblitz](https://stackblitz.com/)

Thanks

**Comment by Haapavuo** [comment]
Closing this issue since cannot reproduce using maplibregl instead of mapboxgl. I currently have no project to easily reproduce this issue and we may assume that it was caused by something else in the project.
